name: Tests

on:
  push:
  pull_request:

jobs:

  vunit-cocotb:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:

    - uses: actions/checkout@v2

    - run: docker build -t vunit/cocotb - < .github/Dockerfile

    - run: docker run --rm -v $(pwd):/src -w /src -e CI vunit/cocotb python3 run.py -v
